%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SCRIPT: PEMFC_Model_Plots.m
% PROJECT: Feasibility of Zero-Emission Cruise Ships
% DESCRIPTION: 
%   Visualizes the static 1D model results for the PEM Fuel Cell.
%   Generates 20 figures characterizing voltage losses, efficiency, 
%   and power density.
% INPUTS: 
%   PEMFC_Results.mat (Generated by PEMFC_Model.m)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

close all; 
clc;

%% 1. INITIALIZATION & SETUP
saveplots = 1; % Set to 1 to save figures as .png and .fig

% Graphics Standards
set(groot, 'defaultLineLineWidth', 2)
set(0, 'DefaultAxesFontSize', 16);       
set(0, 'DefaultTextFontSize', 16);       
set(0, 'DefaultColorbarFontSize', 16);   

% Data Safety Check
if ~exist('j', 'var') || ~exist('H2u', 'var')
    warning('Results not found in workspace. Attempting to load PEMFC_Results.mat...');
    try
        load('PEMFC_Results.mat');
    catch
        error('PEMFC_Results.mat not found. Please run PEMFC_Model.m first.');
    end
end

% Select Hydrogen Utilization for plotting
H2utilization_plot = 0.9; 
uplot = round((H2utilization_plot-H2u(1))/(H2u(end)-H2u(1))*(size(H2u,2)-1)+1);

%% 2. VOLTAGE LOSS ANALYSIS (Figures 1-3)

% Figure 1: Ohmic Loss
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
plot(j, vOhmic(uplot,:));
xticks(0:0.2:jlO2); xlim([0 jlO2]); ylim([0 inf]);
xlabel('Current density [A/cm^2]'); ylabel('Voltage [V]');
legend('Ohmic loss', 'Location', 'southeast');
if saveplots, saveas(gcf, "Fig1.png"); saveas(gcf, "Fig1.fig"); end

% Figure 2: Activation Loss
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
plot(j, vActivation(uplot,:));
xticks(0:0.2:jlO2); xlim([0 jlO2]); ylim([0 inf]);
xlabel('Current density [A/cm^2]'); ylabel('Voltage [V]');
legend('Activation loss', 'Location', 'southeast');
if saveplots, saveas(gcf, "Fig2.png"); saveas(gcf, "Fig2.fig"); end

% Figure 3: Concentration Loss
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
plot(j, vConcentration(uplot,:));
xticks(0:0.2:jlO2); xlim([0 jlO2]); ylim([0 inf]);
xlabel('Current density [A/cm^2]'); ylabel('Voltage [V]');
legend('Concentration loss', 'Location', 'northwest');
if saveplots, saveas(gcf, "Fig3.png"); saveas(gcf, "Fig3.fig"); end

%% 3. POLARIZATION & POWER CURVES (Figures 4-7)

% Figure 4: Cell Voltage (j-V Curve)
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
plot(j, Vcellout(uplot,:))
xticks(0:0.2:jlO2); xlim([0 jlO2]); ylim([0 inf]);
xlabel('Current density [A/cm^2]'); ylabel('Voltage [V]');
legend('Cell voltage');
if saveplots, saveas(gcf, "Fig4.png"); saveas(gcf, "Fig4.fig"); end

% Figure 5: Polarization + Power Density (Dual Axis)
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
yyaxis left
    plot(j, Vcellout(uplot,:));
    xlabel('Current density [A/cm^2]'); ylabel('Voltage [V]');
    ylim([0 inf]); xlim([0 jlO2]);
yyaxis right
    plot(j, Vcellout(uplot,:).*j);
    ylabel('Power density [W/cm^2]');
legend('Cell voltage', 'Power Density', 'Location', 'southeast');
if saveplots, saveas(gcf, "Fig5.png"); saveas(gcf, "Fig5.fig"); saveas(gcf, "Fig5.svg"); end

% Figure 6: Stack Voltage vs Net Power
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
yyaxis left
    plot(iCell, Vout(uplot,:));
    xlabel('Current [A]'); ylabel('Voltage [V]');
    ylim([0 inf]); xlim([0 iCell(end)]);
yyaxis right
    plot(iCell, NetElectricalPowerOut(uplot,:)/1000);
    ylabel('Power [kW]'); ylim([0 250]);
legend('Stack output voltage', 'Net Power Output', 'Location', 'southeast');
if saveplots, saveas(gcf, "Fig6.png"); saveas(gcf, "Fig6.fig"); end

% Figure 7: Power Density Only
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
plot(j, Pdensout(uplot,:));
xticks(0:0.2:jlO2); xlim([0 jlO2]); ylim([0 1.8]);
xlabel('Current density [A/cm^2]'); ylabel('Power density [W/cm2]');
legend('Power Density', 'Location', 'southeast');
if saveplots, saveas(gcf, "Fig7.png"); saveas(gcf, "Fig7.fig"); end

%% 4. THERMAL & AIR MANAGEMENT (Figures 8-10)

% Check for Water Cooling Configuration
IsWaterCooled = exist('WaterCooling','var') && ...
                (strcmpi(WaterCooling,'y') || strcmpi(WaterCooling,'yes'));

if IsWaterCooled
    % Figure 8: Exhaust Temp vs Air Flow
    figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
    yyaxis left
        plot(j, Toutlet(uplot,:)-273);
        ylabel('Exhaust temperature [C]'); xlabel('Current density [A/cm^2]');
        ylim([0 100]); xlim([0 jlO2]);
    yyaxis right
        plot(j, AirSupplyLPM);
        ylabel('Air flow rate [l/min]'); ylim([0 inf]);
    legend('Exhaust temperature', 'Air flow rate', 'Location', 'northwest');
    if saveplots, saveas(gcf, "Fig8.png"); saveas(gcf, "Fig8.fig"); end
    
    % Figure 9: Cooling Water Params
    figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
    yyaxis left
        plot(j, CoolingWatTempOut(uplot,:)-273.15);
        ylabel('Cooling water out temperature [C]'); xlabel('Current density [A/cm^2]');
        ylim([0 100]); xlim([0 jlO2]);
    yyaxis right
        plot(j, CoolingWatFlow(uplot,:)*60);
        ylabel('Cooling water flow rate [l/min]'); ylim([0 inf]);
    legend('Cooling water temp', 'Flow rate', 'Location', 'northwest');
    if saveplots, saveas(gcf, "Fig9.png"); saveas(gcf, "Fig9.fig"); end
else
    % Figure 8 (Alternative): Exhaust Temp vs H2O Title
    figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
    yyaxis left
        plot(j, Toutlet(uplot,:)-273);
        ylabel('Exhaust temperature [C]'); xlabel('Current density [A/cm^2]');
        ylim([0 130]); xlim([0 jlO2]);
    yyaxis right
        plot(j, TitleH2O(uplot,:));
        ylabel('H2O Title'); ylim([0 1]);
    legend('Exhaust temperature', 'H2O title');
    if saveplots, saveas(gcf, "Fig8.png"); saveas(gcf, "Fig8.fig"); end
end

% Figure 10: Air Supply vs Blower Power
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
yyaxis left
    plot(j, AirSupplyLPM);
    xlabel('Current density [A/cm^2]'); ylabel('Cathode Air supply [LPM]');
    ylim([0 inf]); xlim([0 jlO2]);
yyaxis right
    plot(j, BlowerPower/1000);
    ylabel('Blower estimated power [kW]'); ylim([0 inf]);
legend('Cathode Air supply', 'Blower est. power', 'Location', 'northwest');
if saveplots, saveas(gcf, "Fig10.png"); saveas(gcf, "Fig10.fig"); end

%% 5. EFFICIENCY ANALYSIS (Figures 11-13)

% Figure 11: Electrical Efficiency
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
plot(j, ElectricalEff(uplot,:));
xticks(0:0.2:jlO2); xlim([0 jlO2]); ylim([0 1]);
xlabel('Current density [A/cm^2]'); ylabel('Electrical efficiency');
legend('Electrical efficiency', 'Location', 'southeast');
if saveplots, saveas(gcf, "Fig11.png"); saveas(gcf, "Fig11.fig"); end

% Figure 12: Heat Efficiencies
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
plot(j, WaterHeatingEff(uplot,:), j, SpaceHeatingEff(uplot,:), j, HeatEff(uplot,:));
xticks(0:0.2:jlO2); xlim([0 jlO2]); ylim([0 1]);
xlabel('Current density [A/cm^2]'); ylabel('Efficiency');
legend('Water Heating efficiency', 'Space Heating efficiency', 'Total Heat efficiency');
if saveplots, saveas(gcf, "Fig12.png"); saveas(gcf, "Fig12.fig"); end

% Figure 13: Combined CHP Efficiency
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
plot(j, ElectricalEff(uplot,:), j, HeatEff(uplot,:), j, CHPEff(uplot,:));
xticks(0:0.2:jlO2); xlim([0 jlO2]); ylim([0 1]);
xlabel('Current density [A/cm^2]'); ylabel('Efficiency');
legend('Electrical efficiency', 'Heat efficiency', 'CHP efficiency');
if saveplots, saveas(gcf, "Fig13.png"); saveas(gcf, "Fig13.fig"); saveas(gcf, "Fig13.svg"); end

%% 6. POWER & HEAT OUTPUTS (Figures 14-20)

% Figure 14: Net Power & CHP Efficiency
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
yyaxis left
    plot(j, NetTotalPowerOut(uplot,:)/1000);
    xlabel('Current density [A/cm^2]'); ylabel('Power [kW]');
    ylim([0 350]); xlim([0 jlO2]);
yyaxis right
    plot(j, CHPEff(uplot,:));
    ylabel('Efficiency [/LHV]'); ylim([0 1]);
legend('Net Power Output', 'CHP Efficiency', 'location', 'southeast');
if saveplots, saveas(gcf, "Fig14.png"); saveas(gcf, "Fig14.fig"); end

% Figure 15: Electrical Power & Efficiency
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
yyaxis left
    plot(j, NetElectricalPowerOut(uplot,:)/1000);
    xlabel('Current density [A/cm^2]'); ylabel('Power [kW]');
    ylim([0 250]); xlim([0 jlO2]);
yyaxis right
    plot(j, ElectricalEff(uplot,:));
    ylabel('Efficiency [/LHV]'); ylim([0 1]);
legend('Electrical Power', 'Electrical Efficiency', 'location', 'northwest');
if saveplots, saveas(gcf, "Fig15.png"); saveas(gcf, "Fig15.fig"); end

% Figure 16: Heat Breakdown
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
yyaxis left
    plot(j, Q_WaterHeating(uplot,:)./1000, j, Q_SpaceHeating(uplot,:)./1000, j, NetHeatOut(uplot,:)./1000);
    xlabel('Current density [A/cm^2]'); ylabel('Power [kW]');
    ylim([0 inf]); xlim([0 jlO2]);
yyaxis right
    plot(j, HeatEff(uplot,:));
    ylabel('Efficiency [/LHV]'); ylim([0 1]);
legend('Water Heat', 'Space Heat', 'Total Heat', 'Heat efficiency', 'location', 'northwest');
if saveplots, saveas(gcf, "Fig16.png"); saveas(gcf, "Fig16.fig"); end

% Figure 17: Heat Power Density
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]); 
plot(j, NetHeatOut(uplot,:)./(Ncells*CellArea));
xticks(0:0.2:jlO2); xlim([0 jlO2]); ylim([0 inf]);
xlabel('Current density [A/cm^2]'); ylabel('Power density [W/cm^2]');
legend('Heat output power density', 'location', 'northwest');
if saveplots, saveas(gcf, "Fig17.png"); saveas(gcf, "Fig17.fig"); end

% Figure 18: Heat-to-Electricity Ratio
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]); 
plot(j, (NetHeatOut(uplot,:))./NetElectricalPowerOut(uplot,:));
xticks(0:0.2:jlO2); xlim([0 jlO2]); ylim([0 inf]);
xlabel('Current density [A/cm^2]'); ylabel('Heat-to-electricity ratio');
legend('Heat-to-electricity ratio', 'location', 'northwest');
if saveplots, saveas(gcf, "Fig18.png"); saveas(gcf, "Fig18.fig"); end

% Figure 19: Comprehensive Summary (Power & Efficiencies)
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]);
yyaxis left
    plot(j, NetTotalPowerOut(uplot,:)./1000, j, NetElectricalPowerOut(uplot,:)/1000, j, NetHeatOut(uplot,:)./1000);
    xlabel('Current density [A/cm^2]'); ylabel('Power [kW]');
    ylim([0 300]); xlim([0 jlO2]);
yyaxis right
    plot(j, CHPEff(uplot,:), j, ElectricalEff(uplot,:), j, HeatEff(uplot,:));
    ylabel('Efficiency [/LHV]'); ylim([0 1]);
legend('CHP Power', 'Electrical Power', 'Heat', 'CHP efficiency', 'Electrical efficiency', 'Heat efficiency', ...
       'location', 'southoutside', 'orientation', 'horizontal', 'Numcolumns', 3);
if saveplots, saveas(gcf, "Fig19.png"); saveas(gcf, "Fig19.fig"); end

% Figure 20: Heat Recovery Breakdown per Stack
figure; set(gcf, 'Units', 'Normalized', 'OuterPosition', [0.2 0.15 0.45 0.55]); 
plot(j, Q_SpaceHeating(uplot,:)/1000, j, Q_WaterHeating(uplot,:)/1000);
xticks(0:0.2:jlO2); xlim([0 jlO2]); ylim([0 inf]);
xlabel('Current density [A/cm^2]'); ylabel('Power per Stack [kW]');
legend('Coolant HX', 'Exhaust HX', 'location', 'northwest');
if saveplots, saveas(gcf, "Fig20.png"); saveas(gcf, "Fig20.fig"); end

%% 7. RESULTS SUMMARY
[Pmaxu, iPmaxu] = max(Pdensout(uplot,:));
jPmaxu = j(iPmaxu);
VPmaxu = Vcellout(iPmaxu);

fprintf('\n--- RESULTS SUMMARY ---\n');
fprintf('Hydrogen Utilization:   %.2f\n', H2u(uplot));
fprintf('Max Power Density:      %.4f W/cm^2 (at %.4f A/cm^2, %.4f V)\n', Pmaxu, jPmaxu, VPmaxu);
fprintf('Max Net Elec. Power:    %.2f kW per stack\n', NetElectricalPowerOut(uplot,iPmaxu)/1000);
fprintf('Recovered Heat:         %.2f kW per stack\n', NetHeatOut(uplot,iPmaxu)/1000);
fprintf('Efficiencies at Peak:   Elec=%.2f; Heat=%.2f; CHP=%.2f\n', ...
    ElectricalEff(uplot,iPmaxu), HeatEff(uplot,iPmaxu), CHPEff(uplot,iPmaxu));
fprintf('-----------------------\n');